# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/sm7325-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter a52sxq m52xq a73xq,$(TARGET_DEVICE)),)

endif
